// Character data by level
const characterData = {
    elementary_ideograms: [
        { char: '人', pinyin: 'rén', meaning: 'person, people', type: 'pictographic', notes: 'Represents a person standing' },
        { char: '口', pinyin: 'kǒu', meaning: 'mouth, opening', type: 'pictographic', notes: 'Square shape representing a mouth' },
        { char: '日', pinyin: 'rì', meaning: 'sun, day', type: 'pictographic', notes: 'Symbol of the sun with a mark in center' },
        { char: '月', pinyin: 'yuè', meaning: 'moon, month', type: 'pictographic', notes: 'Crescent shape representing the moon' },
        { char: '水', pinyin: 'shuǐ', meaning: 'water', type: 'pictographic', notes: 'Flowing streams of water' },
        { char: '火', pinyin: 'huǒ', meaning: 'fire', type: 'pictographic', notes: 'Flames rising upward' },
        { char: '木', pinyin: 'mù', meaning: 'tree, wood', type: 'pictographic', notes: 'Tree with roots, trunk and branches' },
        { char: '土', pinyin: 'tǔ', meaning: 'earth, soil', type: 'pictographic', notes: 'Ground with something growing from it' },
        { char: '山', pinyin: 'shān', meaning: 'mountain', type: 'pictographic', notes: 'Three peaks representing mountains' },
        { char: '田', pinyin: 'tián', meaning: 'field', type: 'pictographic', notes: 'Divided plot of farmland' },
        { char: '目', pinyin: 'mù', meaning: 'eye', type: 'pictographic', notes: 'Shape of an eye' },
        { char: '手', pinyin: 'shǒu', meaning: 'hand', type: 'pictographic', notes: 'Hand with fingers' },
        { char: '心', pinyin: 'xīn', meaning: 'heart', type: 'pictographic', notes: 'Heart shape' },
        { char: '门', pinyin: 'mén', meaning: 'door, gate', type: 'pictographic', notes: 'A door with two sides' },
        { char: '耳', pinyin: 'ěr', meaning: 'ear', type: 'pictographic', notes: 'Shape of an ear' },
        { char: '女', pinyin: 'nǚ', meaning: 'woman, female', type: 'pictographic', notes: 'Depicts a kneeling woman' },
        { char: '子', pinyin: 'zǐ', meaning: 'child, seed', type: 'pictographic', notes: 'A child figure' },
        { char: '马', pinyin: 'mǎ', meaning: 'horse', type: 'pictographic', notes: 'Horse with mane' },
        { char: '力', pinyin: 'lì', meaning: 'force, power', type: 'pictographic', notes: 'Depicts muscle or tendon' },
        { char: '刀', pinyin: 'dāo', meaning: 'knife', type: 'pictographic', notes: 'Blade shape' }
    ],
    combined_ideograms: [
        { char: '好', pinyin: 'hǎo', meaning: 'good', components: '女 (woman) + 子 (child)', notes: 'A woman with her child symbolizes something good' },
        { char: '明', pinyin: 'míng', meaning: 'bright, clear', components: '日 (sun) + 月 (moon)', notes: 'Sun and moon together represent brightness' },
        { char: '林', pinyin: 'lín', meaning: 'forest', components: '木 (tree) + 木 (tree)', notes: 'Two trees make a forest' },
        { char: '森', pinyin: 'sēn', meaning: 'dense forest', components: '木 (tree) + 木 (tree) + 木 (tree)', notes: 'Three trees make a dense forest' },
        { char: '休', pinyin: 'xiū', meaning: 'rest', components: '人 (person) + 木 (tree)', notes: 'Person leaning against a tree (resting)' },
        { char: '看', pinyin: 'kàn', meaning: 'to look, to see', components: '手 (hand) + 目 (eye)', notes: 'Hand above eye means to look or observe' },
        { char: '炎', pinyin: 'yán', meaning: 'flame, inflammation', components: '火 (fire) + 火 (fire)', notes: 'Two fires represent intense heat' },
        { char: '男', pinyin: 'nán', meaning: 'man, male', components: '田 (field) + 力 (strength)', notes: 'Strength in the fields represents man' },
        { char: '妈', pinyin: 'mā', meaning: 'mother', components: '女 (woman) + 马 (horse)', notes: 'The woman radical with horse phonetic component' },
        { char: '信', pinyin: 'xìn', meaning: 'trust, letter', components: '人 (person) + 言 (speech)', notes: 'A person standing by their word' },
        { char: '囚', pinyin: 'qiú', meaning: 'prisoner', components: '人 (person) + 口 (enclosure)', notes: 'Person inside an enclosure' },
        { char: '国', pinyin: 'guó', meaning: 'country, nation', components: '囗 (enclosure) + 玉 (jade)', notes: 'Jade inside boundaries represents a nation' },
        { char: '思', pinyin: 'sī', meaning: 'to think', components: '田 (field) + 心 (heart)', notes: 'Heart below a field symbolizes thinking/contemplation' },
        { char: '朋', pinyin: 'péng', meaning: 'friend', components: '月 (moon) + 月 (moon)', notes: 'Two moons side by side meaning friend or companion' },
        { char: '忘', pinyin: 'wàng', meaning: 'to forget', components: '亡 (to lose) + 心 (heart)', notes: 'Heart lost means forgotten' },
        { char: '岩', pinyin: 'yán', meaning: 'rock, cliff', components: '山 (mountain) + 石 (stone)', notes: 'Stone on a mountain' },
        { char: '汗', pinyin: 'hàn', meaning: 'sweat', components: '水 (water) + 干 (dry)', notes: 'Water plus stem represents perspiration' },
        { char: '泪', pinyin: 'lèi', meaning: 'tear', components: '水 (water) + 目 (eye)', notes: 'Water from the eye is a tear' },
        { char: '杯', pinyin: 'bēi', meaning: 'cup', components: '木 (wood) + 不 (not)', notes: 'Originally wooden cup' },
        { char: '灯', pinyin: 'dēng', meaning: 'lamp, light', components: '火 (fire) + 丁 (nail)', notes: 'Fire on a stand represents a lamp' }
    ],
    beginner: [
        { char: '我', pinyin: 'wǒ', meaning: 'I, me' },
        { char: '你', pinyin: 'nǐ', meaning: 'you' },
        { char: '他', pinyin: 'tā', meaning: 'he, him' },
        { char: '她', pinyin: 'tā', meaning: 'she, her' },
        { char: '好', pinyin: 'hǎo', meaning: 'good, well' },
        { char: '是', pinyin: 'shì', meaning: 'to be, is, am, are' },
        { char: '不', pinyin: 'bù', meaning: 'no, not' },
        { char: '人', pinyin: 'rén', meaning: 'person, people' },
        { char: '们', pinyin: 'men', meaning: 'plural marker' },
        { char: '一', pinyin: 'yī', meaning: 'one' },
        { char: '二', pinyin: 'èr', meaning: 'two' },
        { char: '三', pinyin: 'sān', meaning: 'three' },
        { char: '四', pinyin: 'sì', meaning: 'four' },
        { char: '五', pinyin: 'wǔ', meaning: 'five' },
        { char: '六', pinyin: 'liù', meaning: 'six' },
        { char: '七', pinyin: 'qī', meaning: 'seven' },
        { char: '八', pinyin: 'bā', meaning: 'eight' },
        { char: '九', pinyin: 'jiǔ', meaning: 'nine' },
        { char: '十', pinyin: 'shí', meaning: 'ten' },
        { char: '中', pinyin: 'zhōng', meaning: 'middle, center, China' }
    ],
    elementary: [
        { char: '时', pinyin: 'shí', meaning: 'time, hour' },
        { char: '间', pinyin: 'jiān', meaning: 'space, between' },
        { char: '年', pinyin: 'nián', meaning: 'year' },
        { char: '月', pinyin: 'yuè', meaning: 'month, moon' },
        { char: '日', pinyin: 'rì', meaning: 'day, sun' },
        { char: '今', pinyin: 'jīn', meaning: 'now, current' },
        { char: '明', pinyin: 'míng', meaning: 'bright, clear' },
        { char: '昨', pinyin: 'zuó', meaning: 'yesterday' },
        { char: '天', pinyin: 'tiān', meaning: 'day, sky, heaven' },
        { char: '下', pinyin: 'xià', meaning: 'below, down, next' },
        { char: '上', pinyin: 'shàng', meaning: 'up, on, above' },
        { char: '前', pinyin: 'qián', meaning: 'before, front' },
        { char: '后', pinyin: 'hòu', meaning: 'after, behind' },
        { char: '左', pinyin: 'zuǒ', meaning: 'left' },
        { char: '右', pinyin: 'yòu', meaning: 'right' },
        { char: '大', pinyin: 'dà', meaning: 'big, large' },
        { char: '小', pinyin: 'xiǎo', meaning: 'small, little' },
        { char: '多', pinyin: 'duō', meaning: 'many, much' },
        { char: '少', pinyin: 'shǎo', meaning: 'few, little' },
        { char: '水', pinyin: 'shuǐ', meaning: 'water' }
    ],
    intermediate: [
        { char: '学', pinyin: 'xué', meaning: 'to learn, study' },
        { char: '生', pinyin: 'shēng', meaning: 'to be born, life' },
        { char: '校', pinyin: 'xiào', meaning: 'school' },
        { char: '教', pinyin: 'jiāo', meaning: 'to teach' },
        { char: '师', pinyin: 'shī', meaning: 'teacher, master' },
        { char: '语', pinyin: 'yǔ', meaning: 'language' },
        { char: '文', pinyin: 'wén', meaning: 'language, culture, writing' },
        { char: '字', pinyin: 'zì', meaning: 'character, word' },
        { char: '工', pinyin: 'gōng', meaning: 'work' },
        { char: '作', pinyin: 'zuò', meaning: 'to do, to make' },
        { char: '开', pinyin: 'kāi', meaning: 'to open' },
        { char: '始', pinyin: 'shǐ', meaning: 'to begin' },
        { char: '结', pinyin: 'jié', meaning: 'to tie, to bind' },
        { char: '束', pinyin: 'shù', meaning: 'to bind, bundle' },
        { char: '朋', pinyin: 'péng', meaning: 'friend' },
        { char: '友', pinyin: 'yǒu', meaning: 'friend' },
        { char: '家', pinyin: 'jiā', meaning: 'home, family' },
        { char: '国', pinyin: 'guó', meaning: 'country, nation' },
        { char: '城', pinyin: 'chéng', meaning: 'city, town' },
        { char: '市', pinyin: 'shì', meaning: 'market, city' }
    ],
    advanced: [
        { char: '经', pinyin: 'jīng', meaning: 'classics, scripture, to pass through' },
        { char: '济', pinyin: 'jì', meaning: 'economy, to cross a river' },
        { char: '政', pinyin: 'zhèng', meaning: 'government, politics' },
        { char: '治', pinyin: 'zhì', meaning: 'to govern, to manage' },
        { char: '法', pinyin: 'fǎ', meaning: 'law, method' },
        { char: '律', pinyin: 'lǜ', meaning: 'law, rule' },
        { char: '责', pinyin: 'zé', meaning: 'responsibility, to blame' },
        { char: '任', pinyin: 'rèn', meaning: 'to appoint, duty' },
        { char: '科', pinyin: 'kē', meaning: 'subject, science, branch' },
        { char: '技', pinyin: 'jì', meaning: 'skill, technique' },
        { char: '术', pinyin: 'shù', meaning: 'art, technique, method' },
        { char: '环', pinyin: 'huán', meaning: 'ring, circle, to surround' },
        { char: '境', pinyin: 'jìng', meaning: 'border, boundary, environment' },
        { char: '保', pinyin: 'bǎo', meaning: 'to protect, to ensure' },
        { char: '护', pinyin: 'hù', meaning: 'to protect, to guard' },
        { char: '发', pinyin: 'fā', meaning: 'to send out, to develop' },
        { char: '展', pinyin: 'zhǎn', meaning: 'to unfold, to expand' },
        { char: '创', pinyin: 'chuàng', meaning: 'to begin, to initiate' },
        { char: '新', pinyin: 'xīn', meaning: 'new' },
        { char: '未', pinyin: 'wèi', meaning: 'not yet, haven\'t' }
    ]
};